'use client';

import { useEffect, useState } from 'react';
import type { PersonalizedLearningPathOutput } from '@/ai/flows/personalized-learning-path';
import { generatePersonalizedLearningPath } from '@/ai/flows/personalized-learning-path';
import type { Student } from '@/lib/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Lightbulb, Book, CheckSquare } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { resources, quizzes } from '@/lib/data';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

/**
 * A client component responsible for fetching and displaying a student's
 * personalized learning path generated by a Genkit AI flow.
 *
 * @param {object} props - The component props.
 * @param {Student} props.student - The student data object, used as input for the AI flow.
 */
export function PersonalizedPathClient({ student }: { student: Student }) {
  // State to hold the generated learning path.
  const [learningPath, setLearningPath] = useState<PersonalizedLearningPathOutput | null>(null);
  // State to manage the loading status.
  const [isLoading, setIsLoading] = useState(true);
  // State to hold any potential errors during the API call.
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    /**
     * An async function to call the Genkit flow to generate the learning path.
     * It runs once when the component mounts.
     */
    async function getPath() {
      try {
        setIsLoading(true);
        setError(null);
        // Prepare the input for the AI flow based on the student's data.
        const input = {
          studentId: student.id,
          gradeLevel: student.grade,
          completedLessons: student.completedLessons,
          quizScores: student.quizScores,
        };
        // Call the server action that triggers the Genkit flow.
        const path = await generatePersonalizedLearningPath(input);
        setLearningPath(path);
      } catch (e) {
        setError('Could not generate your learning path. Please try again later.');
        console.error(e);
      } finally {
        setIsLoading(false);
      }
    }
    // Invoke the function to fetch the path.
    getPath();
  }, [student]); // The effect depends on the student prop.

  // Display a skeleton loader while the data is being fetched.
  if (isLoading) {
    return <PersonalizedPathSkeleton />;
  }

  // Display an error message if the API call failed.
  if (error) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="text-accent" />
            Your Next Adventure
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  // Return null if no learning path was generated (and no error occurred).
  if (!learningPath) {
    return null;
  }
  
  // Filter the mock data to get the full details of recommended resources and quizzes.
  const recommendedResources = resources.filter(r => learningPath.recommendedLessons.includes(r.id));
  const recommendedQuizzes = quizzes.filter(q => learningPath.recommendedQuizzes.includes(q.id));

  // Render the personalized learning path.
  return (
    <Card className="bg-primary/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 font-headline">
          <Lightbulb className="text-accent" />
          Your Next Adventure
        </CardTitle>
        {/* Display the AI-generated explanation for the recommendations. */}
        <CardDescription>{learningPath.explanation}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Section for recommended lessons */}
        <div>
          <h4 className="font-semibold mb-2 flex items-center gap-2"><Book className="w-4 h-4" />Recommended Lessons</h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {recommendedResources.length > 0 ? recommendedResources.map(res => (
                <Card key={res.id} className="p-3 flex justify-between items-center">
                    <div>
                        <p className="font-medium">{res.title}</p>
                        <p className="text-sm text-muted-foreground">Grade {res.grade} &middot; {res.topic}</p>
                    </div>
                    <Button size="sm" variant="ghost" asChild>
                        <Link href={`/student/resources/${res.id}`}>Start</Link>
                    </Button>
                </Card>
            )) : <p className="text-sm text-muted-foreground">No new lessons recommended. Great job!</p>}
          </div>
        </div>
        {/* Section for recommended quizzes */}
        <div>
          <h4 className="font-semibold mb-2 flex items-center gap-2"><CheckSquare className="w-4 h-4"/>Recommended Quizzes</h4>
           <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {recommendedQuizzes.length > 0 ? recommendedQuizzes.map(quiz => (
                <Card key={quiz.id} className="p-3 flex justify-between items-center">
                    <div>
                        <p className="font-medium">{quiz.title}</p>
                        <p className="text-sm text-muted-foreground">Grade {quiz.grade} &middot; {quiz.topic}</p>
                    </div>
                    <Button size="sm" variant="ghost" asChild>
                        <Link href="/student/resources">Start</Link>
                    </Button>
                </Card>
            )) : <p className="text-sm text-muted-foreground">No new quizzes recommended. You're on a roll!</p>}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

/**
 * A skeleton component to show a loading state while the personalized path is being generated.
 * This provides a better user experience by indicating that content is on its way.
 */
function PersonalizedPathSkeleton() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="text-accent" />
          Your Next Adventure
        </CardTitle>
        <Skeleton className="h-4 w-3/4" />
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
            <Skeleton className="h-5 w-1/3 mb-2" />
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <Skeleton className="h-16 w-full" />
                <Skeleton className="h-16 w-full" />
            </div>
        </div>
        <div>
            <Skeleton className="h-5 w-1/3 mb-2" />
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <Skeleton className="h-16 w-full" />
            </div>
        </div>
      </CardContent>
    </Card>
  );
}
